version: '3.8'

services:
  postgis:
    image: postgis/postgis:latest
    container_name: geowiki_db
    restart: always
    environment:
    - POSTGRES_DB=geowiki
    - POSTGRES_USER=geowiki
    - POSTGRES_PASSWORD=secret
    ports:
      - "25432:5432"
