name: Build and Push to Artifact Registry

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      REPOSITORY_NAME:
        required: true
        type: string
      GAR_LOCATION:
        required: true
        type: string
    secrets:
      GCP_PROJECT_ID:
        required: true
      GCP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      GCP_SERVICE_ACCOUNT:
        required: true

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ inputs.GAR_LOCATION }}-docker.pkg.dev

      - name: Build Docker image
        run: >
          docker build . --tag "${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ inputs.REPOSITORY_NAME }}/${{ inputs.IMAGE_NAME }}:latest"

      - name: Push Docker image
        run: >
          docker push "${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ inputs.REPOSITORY_NAME }}/${{ inputs.IMAGE_NAME }}:latest"