name: Main

on:
  push:
    branches:
      - main
      - dev

# Permissions are still required here for the OIDC token
permissions:
  contents: 'read'
  id-token: 'write'

jobs:
    build-and-push:
      name: Build and Push Docker Image
      runs-on: ubuntu-latest
      environment: ${{ github.ref_name }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Authenticate to Google Cloud
          id: auth
          uses: google-github-actions/auth@v2
          with:
            workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
            service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

        - name: Configure Docker
          run: gcloud auth configure-docker ${{ vars.GAR_LOCATION }}-docker.pkg.dev

        - name: Build Docker image
          run: >
            docker build . --tag "${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.REPOSITORY_NAME }}/${{ vars.IMAGE_NAME }}:latest"

        - name: Push Docker image
          run: >
            docker push "${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.REPOSITORY_NAME }}/${{ vars.IMAGE_NAME }}:latest"

    terraform:
      name: Apply Terraform
      runs-on: ubuntu-latest
      environment: ${{ github.ref_name }}
      # Set TF_VAR_ environment variables, which Terraform automatically uses
      env:
        TF_VAR_GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_GCP_REGION: ${{ vars.GCP_REGION }}
        TF_VAR_REPOSITORY_NAME: ${{ vars.REPOSITORY_NAME }}
        TF_VAR_IMAGE_NAME: ${{ vars.IMAGE_NAME }}
        TF_VAR_FRONTEND_BUCKET_NAME: ${{ vars.FRONTEND_BUCKET_NAME }}
        TF_VAR_CLOUD_RUN_SERVICE_NAME: ${{ vars.CLOUD_RUN_SERVICE_NAME }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v2
          with:
            workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
            service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Terraform Init
          id: init
          working-directory: ./infra
          run: terraform init

        - name: Terraform Apply
          id: apply
          working-directory: ./infra
          run: terraform apply -auto-approve